export const homeObjOne = {
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    OriginalHero: true,
    HeroCard:'About',
    title: 'A propos',
    headingFive: "",
    OriginalHero: true,
    HeroCard:'',
    topLine: 'Marjorie',
    headLine: "Votre esthèticienne à domicile",
    description: "Esthèticienne diplômée et expérimentée met son savoir-faire et son expérience au service de votre bien-être.",
    description2: "En faisant appel à moi, c'est l'institut qui vient à vous. Null besoin de faire garder vos enfants et fini le stress des embouteillages. Je me déplace à votre domicile, équipée de tout le matériel professionnel nécessaire et vous propose une large gamme de soins esthètiques.",
    buttonLabel: "Commencer",
    imgStart: '',
    img: '/Images/about/about1.jpg',
    alt: 'A propos'
}
export const homeObjTwo = {
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    OriginalHero: false,
    HeroCard:'Pricing',
    title: 'Nos Prestations',
    headingFive: "Epilations, manucures, pédicures massages et autres soins du corps, des mains et des pieds font parti de nos prestations à domicile. ",
    topLine: 'Simplifiez-vous la vie',
    headLine: "Votre esthèticienne à domicile",
    description: "Quel est le meilleur endroit mise à part chez vous pour être à laise lors d'une épillation, soins du corps ou autres service et prestrations",
    buttonLabel: "Commencer",
    imgStart: 'start',
    img: 'images/about/about1.jpg',
    alt: 'A propos'
}
export const homeObjThree = {
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    button: null,
    OriginalHero: true,
    HeroCard:'Testimonial',
    title: 'Témoignages',
    headingFive: "",
    topLine: '',
    headLine: "",
    description: "",
    buttonLabel: "",
    imgStart: '',
    img: null,
    alt: null
}
export const homeObjFour = {
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    OriginalHero: false,
    HeroCard:'Pricing',
    title: 'Nos produits/ Idées cadeaux',
    headingFive: "Marjorie votre esthèticienne à domicile",
    topLine: 'Simplifiez-vous la vie',
    headLine: "Votre esthèticienne à domicile",
    description: "Quel est le meilleur endroit mise à part chez vous pour être à laise lors d'une épillation, soins du corps ou autres service et prestrations",
    buttonLabel: "Commencer",
    imgStart: 'start',
    img: 'images/about/about1.jpg',
    alt: 'A propos'
}
export const homeObjFive = {
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    OriginalHero: true,
    button: null,
    HeroCard:'Cards',
    title: 'Le blog',
    headingFive: "Quelques infos sur le soin beauté. Astuces, produits miracles et autres.",
    topLine: '',
    headLine: "",
    description: "",
    buttonLabel: "",
    imgStart: '',
    img: null,
    alt: null
}
